services:
  backend:
    build:
      context: ./server/projectRAG
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/projectRAG:/app
    env_file:
      - path: ./server/projectRAG/.env
        required: true

  frontend:
    build:
      context: ./frontend/rag-app
      dockerfile: Dockerfile.frontend
    ports:
      - "5678:5678"
    volumes:
      - ./frontend/rag-app/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
